/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacksandqueues;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testNode() {
        Node four = new Node(4);
        Node five = new Node(5);

        //test node creations, tooString and getValue
        assertEquals("value = 4", four.toString());
        assertEquals(4, four.getValue());
        assertEquals("value = 5", five.toString());
        assertEquals(5, five.getValue());
        //test setValue
        five.setValue(6);
        assertEquals(6, five.getValue());
        five.setValue(7);
        assertEquals(7,five.getValue());
    }
    
    @Test
    public void testStack() {
        Stack testStack = new Stack();
        Stack emptyStack = new Stack();

        testStack.push(4);
        testStack.push(8);
        testStack.push(16);

        //toString test
        assertEquals("{16} -> {8} -> {4} -> NULL", testStack.toString());
        //push test
        testStack.push(24);
        assertEquals("{24} -> {16} -> {8} -> {4} -> NULL", testStack.toString());
        //empty stack test
        assertEquals("NULL", emptyStack.toString());
    }

}